// Class: ReadBDT_singleClass_boosted_boosted_2017
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_singleClass_boosted_boosted_2017
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : ceballos
Date           : Tue May 29 06:16:34 2018
Host           : Linux cmsbuild20.cern.ch 2.6.32-696.23.1.el6.x86_64 #1 SMP Wed Mar 14 11:28:37 CET 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ceballos/cms/cmssw/048/CMSSW_9_4_6/src
Training events: 9540
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "400" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "10000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "1.000000e-01" [Learning rate  for AdaBoost algorithm]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
SeparationType: "misclassificationerror" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
nIsojet                       nIsojet                       nIsojet                       nIsojet                                                         'F'    [0,7]
fjPt                          fjPt                          fjPt                          fjPt                                                            'F'    [250.05796814,1592.09289551]
MSD                           MSD                           MSD                           MSD                                                             'F'    [80.0121459961,149.853881836]
Tau21SD                       Tau21SD                       Tau21SD                       Tau21SD                                                         'F'    [0.0746132731438,1]
ptBalanceZHFJ                 ptBalanceZHFJ                 ptBalanceZHFJ                 ptBalanceZHFJ                                                   'F'    [0.455623656511,4.66275644302]
dEtaZHFJ                      dEtaZHFJ                      dEtaZHFJ                      dEtaZHFJ                                                        'F'    [0.000291109085083,4.27346277237]
dPhiZHFJ                      dPhiZHFJ                      dPhiZHFJ                      dPhiZHFJ                                                        'F'    [2.50001072884,3.14159107208]
mTZHFJ                        mTZHFJ                        mTZHFJ                        mTZHFJ                                                          'F'    [537.972839355,5224.61816406]
ptBalanceL1L2                 ptBalanceL1L2                 ptBalanceL1L2                 ptBalanceL1L2                                                   'F'    [0.158768773079,61.4080543518]
dRL1L2                        dRL1L2                        dRL1L2                        dRL1L2                                                          'F'    [0.141968935728,2.1290268898]
ZBosonPt                      ZBosonPt                      ZBosonPt                      ZBosonPt                                                        'F'    [250.03062439,1371.78540039]
lepton1Pt                     lepton1Pt                     lepton1Pt                     lepton1Pt                                                       'F'    [43.154460907,1290.32702637]
lepton2Pt                     lepton2Pt                     lepton2Pt                     lepton2Pt                                                       'F'    [10.0233974457,531.937011719]
deltaM                        deltaM                        deltaM                        deltaM                                                          'F'    [4.6594239393e-05,15.9538431168]
CosThetaCS                    CosThetaCS                    CosThetaCS                    CosThetaCS                                                      'F'    [-0.999999523163,0.999855995178]
nIsoBjet                      nIsoBjet                      nIsoBjet                      nIsoBjet                                                        'F'    [0,3]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_singleClass_boosted_boosted_2017Node
   
#ifndef BDT_singleClass_boosted_boosted_2017Node__def
#define BDT_singleClass_boosted_boosted_2017Node__def
   
class BDT_singleClass_boosted_boosted_2017Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_singleClass_boosted_boosted_2017Node ( BDT_singleClass_boosted_boosted_2017Node* left,BDT_singleClass_boosted_boosted_2017Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_singleClass_boosted_boosted_2017Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_singleClass_boosted_boosted_2017Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_singleClass_boosted_boosted_2017Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_singleClass_boosted_boosted_2017Node*   fLeft;     // pointer to the left daughter node
   BDT_singleClass_boosted_boosted_2017Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_singleClass_boosted_boosted_2017Node::~BDT_singleClass_boosted_boosted_2017Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_singleClass_boosted_boosted_2017Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_singleClass_boosted_boosted_2017Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_singleClass_boosted_boosted_2017 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_singleClass_boosted_boosted_2017( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_singleClass_boosted_boosted_2017" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "nIsojet", "fjPt", "MSD", "Tau21SD", "ptBalanceZHFJ", "dEtaZHFJ", "dPhiZHFJ", "mTZHFJ", "ptBalanceL1L2", "dRL1L2", "ZBosonPt", "lepton1Pt", "lepton2Pt", "deltaM", "CosThetaCS", "nIsoBjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_singleClass_boosted_boosted_2017() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_singleClass_boosted_boosted_2017Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_singleClass_boosted_boosted_2017::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_singleClass_boosted_boosted_2017Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_singleClass_boosted_boosted_2017Node*)current->GetRight();
         else current=(BDT_singleClass_boosted_boosted_2017Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_singleClass_boosted_boosted_2017::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.0849983140161878);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360563,-99) , 
6, 2.86855, 0, 0, 0.641777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239538,-99) , 
9, 0.530975, 1, 0, 0.323485,-99) , 
2, 100.243, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.0763238);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378298,-99) , 
6, 2.86907, 0, 0, 0.639073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268929,-99) , 
9, 0.530975, 1, 0, 0.344571,-99) , 
2, 102.094, 0, 0, 0.496796,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.0733094);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343979,-99) , 
12, 46.5205, 0, 0, 0.648431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315742,-99) , 
12, 144.047, 0, 0, 0.369483,-99) , 
2, 105.125, 0, 0, 0.494432,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0680764);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35593,-99) , 
7, 1171.17, 1, 0, 0.611297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282475,-99) , 
9, 0.530975, 1, 0, 0.347893,-99) , 
2, 100.243, 0, 0, 0.494395,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0658775);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388516,-99) , 
5, 1.12669, 1, 0, 0.626713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293497,-99) , 
4, 0.920045, 1, 0, 0.382155,-99) , 
2, 105.125, 0, 0, 0.491514,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0602983);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436535,-99) , 
6, 3.00969, 0, 0, 0.603022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278882,-99) , 
4, 0.920045, 1, 0, 0.368708,-99) , 
2, 102.094, 0, 0, 0.489783,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0591288);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295855,-99) , 
9, 0.839814, 1, 0, 0.592315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319196,-99) , 
12, 144.047, 0, 0, 0.359665,-99) , 
2, 100.243, 0, 0, 0.489193,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0649844);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.24081,-99) , 
9, 0.839858, 1, 0, 0.580432,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315768,-99) , 
6, 3.12286, 0, 0, 0.344761,-99) , 
3, 0.343596, 1, 0, 0.486692,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0589753);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319073,-99) , 
3, 0.468696, 1, 0, 0.612445,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342205,-99) , 
7, 702.196, 1, 0, 0.398976,-99) , 
2, 107.01, 0, 0, 0.484208,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0643773);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389235,-99) , 
8, 4.1457, 1, 0, 0.569727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3093,-99) , 
8, 1.36994, 1, 0, 0.354605,-99) , 
5, 0.795449, 1, 0, 0.483925,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0540108);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304483,-99) , 
2, 131.101, 1, 0, 0.594839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325942,-99) , 
3, 0.273915, 1, 0, 0.395977,-99) , 
2, 105.125, 0, 0, 0.484518,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0518364);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412465,-99) , 
5, 0.935404, 1, 0, 0.596345,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359935,-99) , 
7, 701.598, 1, 0, 0.406737,-99) , 
2, 107.01, 0, 0, 0.482122,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0575778);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370006,-99) , 
0, 1.0002, 1, 0, 0.562041,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292292,-99) , 
4, 0.859952, 1, 0, 0.358001,-99) , 
2, 98.0295, 0, 0, 0.483715,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0540429);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250174,-99) , 
9, 0.839277, 1, 0, 0.558926,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347942,-99) , 
6, 3.12286, 0, 0, 0.37333,-99) , 
3, 0.333511, 1, 0, 0.481392,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0572772);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356712,-99) , 
4, 1.14847, 1, 0, 0.554055,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325767,-99) , 
8, 1.36994, 1, 0, 0.367565,-99) , 
5, 0.795449, 1, 0, 0.479689,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0456943);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307095,-99) , 
2, 131.099, 1, 0, 0.582561,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372415,-99) , 
7, 701.598, 1, 0, 0.410721,-99) , 
2, 107.01, 0, 0, 0.479007,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0508749);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313266,-99) , 
3, 0.514498, 1, 0, 0.553184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347737,-99) , 
3, 0.192579, 1, 0, 0.379643,-99) , 
8, 2.96983, 1, 0, 0.478713,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0432215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381705,-99) , 
5, 1.12375, 1, 0, 0.573987,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370069,-99) , 
9, 0.530975, 1, 0, 0.414228,-99) , 
2, 107.01, 0, 0, 0.477547,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0508417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44474,-99) , 
0, 0.00069993, 1, 0, 0.543008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298655,-99) , 
9, 0.542697, 1, 0, 0.363959,-99) , 
2, 97.5058, 0, 0, 0.477535,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.04744);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349222,-99) , 
3, 0.467863, 1, 0, 0.543936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310766,-99) , 
4, 0.859952, 1, 0, 0.369127,-99) , 
2, 97.5058, 0, 0, 0.480145,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0495544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400305,-99) , 
8, 4.1457, 1, 0, 0.540694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343292,-99) , 
8, 1.37521, 1, 0, 0.380998,-99) , 
5, 0.795449, 1, 0, 0.477191,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0405843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305447,-99) , 
2, 131.099, 1, 0, 0.562637,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382448,-99) , 
14, 0.324575, 0, 0, 0.421836,-99) , 
2, 107.01, 0, 0, 0.477664,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0436332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31011,-99) , 
5, 1.29963, 1, 0, 0.53919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370896,-99) , 
6, 3.12286, 0, 0, 0.390816,-99) , 
3, 0.333511, 1, 0, 0.477194,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0459469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397977,-99) , 
13, 0.975206, 0, 0, 0.558568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401326,-99) , 
3, 0.192532, 1, 0, 0.428154,-99) , 
8, 1.95319, 1, 0, 0.47616,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0467406);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445169,-99) , 
0, 0.00069993, 1, 0, 0.533812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298882,-99) , 
9, 0.542697, 1, 0, 0.363386,-99) , 
2, 95.5364, 0, 0, 0.480378,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0435704);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35069,-99) , 
3, 0.467863, 1, 0, 0.53477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311537,-99) , 
4, 0.859952, 1, 0, 0.368139,-99) , 
2, 95.5364, 0, 0, 0.482645,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0440472);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4236,-99) , 
3, 0.334996, 1, 0, 0.571568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368113,-99) , 
5, 0.515398, 1, 0, 0.437534,-99) , 
14, 0.323373, 0, 0, 0.479391,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0403821);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404661,-99) , 
3, 0.400895, 1, 0, 0.571051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359021,-99) , 
7, 836.014, 1, 0, 0.439287,-99) , 
14, 0.323373, 0, 0, 0.480375,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0381806);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438028,-99) , 
3, 0.334996, 1, 0, 0.567677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407433,-99) , 
14, -0.717783, 1, 0, 0.43944,-99) , 
14, 0.323373, 0, 0, 0.479377,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0411907);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40973,-99) , 
2, 122.916, 1, 0, 0.547915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284034,-99) , 
4, 1.01007, 1, 0, 0.429898,-99) , 
2, 105.125, 0, 0, 0.482522,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0380302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394969,-99) , 
2, 93.5738, 0, 0, 0.565188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381626,-99) , 
5, 0.515398, 1, 0, 0.440806,-99) , 
14, 0.323373, 0, 0, 0.479384,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0361219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420812,-99) , 
2, 122.519, 1, 0, 0.548433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417441,-99) , 
13, 5.42309, 0, 0, 0.433402,-99) , 
2, 107.01, 0, 0, 0.479188,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0393603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381023,-99) , 
5, 1.12616, 1, 0, 0.535765,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373907,-99) , 
6, 3.12079, 0, 0, 0.400542,-99) , 
8, 3.2148, 1, 0, 0.48225,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.035048);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364634,-99) , 
3, 0.472933, 1, 0, 0.562959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376099,-99) , 
7, 833.671, 1, 0, 0.444818,-99) , 
14, 0.323373, 0, 0, 0.481456,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0384737);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402655,-99) , 
13, 0.974102, 0, 0, 0.574062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.669425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429561,-99) , 
3, 0.17287, 1, 0, 0.448565,-99) , 
12, 140.802, 0, 0, 0.47998,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0400183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453957,-99) , 
0, 0.00069993, 1, 0, 0.528869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331442,-99) , 
9, 0.538922, 1, 0, 0.388365,-99) , 
2, 95.5364, 0, 0, 0.485344,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0340989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398948,-99) , 
5, 1.12616, 1, 0, 0.534139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387478,-99) , 
2, 115.057, 0, 0, 0.415954,-99) , 
8, 3.2148, 1, 0, 0.487401,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0328803);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412787,-99) , 
2, 93.5738, 0, 0, 0.562396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417565,-99) , 
2, 111.089, 0, 0, 0.452058,-99) , 
14, 0.323373, 0, 0, 0.486422,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0327425);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419732,-99) , 
6, 2.98365, 0, 0, 0.530396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399589,-99) , 
6, 3.12079, 0, 0, 0.421995,-99) , 
8, 3.2148, 1, 0, 0.487563,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0324676);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375539,-99) , 
3, 0.472933, 1, 0, 0.55813,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390473,-99) , 
7, 836.014, 1, 0, 0.455602,-99) , 
14, 0.323373, 0, 0, 0.487545,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0353532);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362876,-99) , 
3, 0.484426, 1, 0, 0.52457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346821,-99) , 
9, 0.538922, 1, 0, 0.399821,-99) , 
2, 95.5364, 0, 0, 0.486142,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0308107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362684,-99) , 
2, 122.629, 1, 0, 0.551167,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426539,-99) , 
14, -0.717783, 1, 0, 0.452692,-99) , 
14, 0.323373, 0, 0, 0.483299,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0402623);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370436,-99) , 
5, 1.12616, 1, 0, 0.524477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383307,-99) , 
12, 141.608, 0, 0, 0.41798,-99) , 
4, 1.04919, 1, 0, 0.484563,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0331036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419343,-99) , 
2, 122.519, 1, 0, 0.539487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429978,-99) , 
13, 5.42309, 0, 0, 0.447307,-99) , 
2, 107.01, 0, 0, 0.483997,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.034763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400887,-99) , 
13, 0.975206, 0, 0, 0.543558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43029,-99) , 
7, 701.572, 1, 0, 0.454165,-99) , 
8, 1.95319, 1, 0, 0.486918,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0304826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30679,-99) , 
4, 0.779602, 0, 0, 0.523148,-99) , 
NN(
0, 
0, 
0, 0.00059994, 1, -1, 0.397261,-99) , 
12, 66.3322, 0, 0, 0.489507,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0298748);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408915,-99) , 
14, 0.866615, 1, 0, 0.549819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401454,-99) , 
7, 833.671, 1, 0, 0.459003,-99) , 
14, 0.323373, 0, 0, 0.487161,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0372555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385553,-99) , 
1, 327.973, 0, 0, 0.534153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315366,-99) , 
4, 1.01007, 1, 0, 0.447867,-99) , 
2, 105.125, 0, 0, 0.486357,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0288229);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441476,-99) , 
3, 0.334996, 1, 0, 0.543307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412461,-99) , 
5, 0.515398, 1, 0, 0.456063,-99) , 
14, 0.323373, 0, 0, 0.483089,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0332271);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40324,-99) , 
13, 1.19222, 0, 0, 0.558746,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441024,-99) , 
3, 0.192584, 1, 0, 0.461693,-99) , 
12, 143.776, 0, 0, 0.483818,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0342958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420763,-99) , 
2, 122.496, 1, 0, 0.533836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32942,-99) , 
4, 1.01049, 1, 0, 0.451516,-99) , 
2, 105.125, 0, 0, 0.488259,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0282433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435839,-99) , 
14, 0.801752, 1, 0, 0.546198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435451,-99) , 
14, -0.717783, 1, 0, 0.458814,-99) , 
14, 0.323373, 0, 0, 0.485808,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0326399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39372,-99) , 
1, 327.973, 0, 0, 0.533069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335629,-99) , 
4, 1.01385, 1, 0, 0.451589,-99) , 
2, 105.125, 0, 0, 0.487959,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0315812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453203,-99) , 
11, 266.875, 1, 0, 0.528981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387145,-99) , 
7, 769.8, 1, 0, 0.449554,-99) , 
2, 105.125, 0, 0, 0.485002,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0307918);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400772,-99) , 
2, 125.188, 1, 0, 0.530181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431628,-99) , 
13, 5.40085, 0, 0, 0.450316,-99) , 
2, 105.125, 0, 0, 0.485955,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.026831);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399774,-99) , 
10, 296.036, 0, 0, 0.545097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419964,-99) , 
7, 800.867, 1, 0, 0.462056,-99) , 
14, 0.323373, 0, 0, 0.487631,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0312496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.732644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42349,-99) , 
12, 181.515, 1, 0, 0.560728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45025,-99) , 
3, 0.17287, 1, 0, 0.46583,-99) , 
12, 143.776, 0, 0, 0.487264,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0291687);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308094,-99) , 
4, 0.779602, 0, 0, 0.523038,-99) , 
NN(
0, 
0, 
0, 0.00059994, 1, -1, 0.410027,-99) , 
12, 66.3322, 0, 0, 0.492547,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0347876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398519,-99) , 
6, 2.98307, 0, 0, 0.520212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283915,-99) , 
2, 97.1449, 0, 0, 0.4031,-99) , 
10, 302.187, 0, 0, 0.490359,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0271468);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431431,-99) , 
14, 0.801752, 1, 0, 0.541334,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397005,-99) , 
4, 1.02984, 1, 0, 0.463306,-99) , 
14, 0.323373, 0, 0, 0.487344,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0288087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.831826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400226,-99) , 
12, 76.1545, 0, 0, 0.612573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441049,-99) , 
2, 111.089, 0, 0, 0.470692,-99) , 
13, 5.39987, 0, 0, 0.48637,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0316153);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404272,-99) , 
13, 0.975206, 0, 0, 0.537006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404014,-99) , 
6, 3.06259, 0, 0, 0.461985,-99) , 
8, 1.95319, 1, 0, 0.488989,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0303356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411909,-99) , 
13, 0.975206, 0, 0, 0.535497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363579,-99) , 
5, 0.914658, 1, 0, 0.461996,-99) , 
8, 1.95319, 1, 0, 0.488424,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0266587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.856161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404008,-99) , 
2, 111.784, 1, 0, 0.613628,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444601,-99) , 
6, 3.10355, 0, 0, 0.47088,-99) , 
13, 5.39987, 0, 0, 0.486403,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.029036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454446,-99) , 
13, 2.31215, 0, 0, 0.53719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445972,-99) , 
6, 2.92529, 1, 0, 0.461645,-99) , 
8, 1.95319, 1, 0, 0.488755,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0324271);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462588,-99) , 
11, 268.745, 1, 0, 0.52259,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295894,-99) , 
2, 97.1449, 0, 0, 0.408137,-99) , 
10, 302.187, 0, 0, 0.493263,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0316802);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371355,-99) , 
15, 0.00029997, 1, 0, 0.524908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302694,-99) , 
2, 97.1449, 0, 0, 0.407688,-99) , 
10, 302.187, 0, 0, 0.494901,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0295793);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416667,-99) , 
6, 2.98307, 0, 0, 0.519851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381159,-99) , 
2, 111.786, 0, 0, 0.407247,-99) , 
10, 302.187, 0, 0, 0.491046,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0260495);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41064,-99) , 
12, 75.9656, 0, 0, 0.626972,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416638,-99) , 
3, 0.333511, 1, 0, 0.473336,-99) , 
13, 5.39987, 0, 0, 0.489647,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0228173);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.781295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464312,-99) , 
5, 0.370053, 0, 0, 0.628088,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460578,-99) , 
3, 0.17288, 1, 0, 0.472479,-99) , 
13, 5.39987, 0, 0, 0.488931,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.028455);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434933,-99) , 
10, 302.187, 0, 0, 0.517787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.155906,-99) , 
5, 1.88842, 1, 0, 0.493093,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0293084);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344711,-99) , 
2, 122.49, 1, 0, 0.545102,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42124,-99) , 
7, 800.867, 1, 0, 0.466,-99) , 
14, 0.323373, 0, 0, 0.490277,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0232365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465466,-99) , 
5, 0.370053, 0, 0, 0.635516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450573,-99) , 
2, 112.499, 0, 0, 0.472859,-99) , 
13, 5.39987, 0, 0, 0.489723,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0270534);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330835,-99) , 
4, 0.77954, 0, 0, 0.515899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162229,-99) , 
5, 1.88842, 1, 0, 0.492087,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0228937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465636,-99) , 
5, 0.370053, 0, 0, 0.634799,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459618,-99) , 
3, 0.17288, 1, 0, 0.470551,-99) , 
13, 5.39987, 0, 0, 0.487397,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0299997);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415583,-99) , 
11, 183.431, 0, 0, 0.541345,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43638,-99) , 
1, 321.715, 1, 0, 0.464367,-99) , 
8, 1.95319, 1, 0, 0.491613,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.027104);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437594,-99) , 
10, 302.187, 0, 0, 0.516598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167459,-99) , 
5, 1.88842, 1, 0, 0.493202,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0220874);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.819292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472571,-99) , 
11, 303.893, 1, 0, 0.645443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45085,-99) , 
6, 3.10355, 0, 0, 0.473194,-99) , 
13, 5.39987, 0, 0, 0.490529,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0212234);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.818083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47453,-99) , 
5, 0.36559, 0, 0, 0.646016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461048,-99) , 
2, 117.437, 0, 0, 0.475356,-99) , 
13, 5.39987, 0, 0, 0.492487,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0273604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384945,-99) , 
3, 0.52005, 1, 0, 0.518667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.172393,-99) , 
5, 1.88842, 1, 0, 0.495584,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0199069);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646917,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464528,-99) , 
3, 0.17288, 1, 0, 0.474219,-99) , 
13, 5.39987, 0, 0, 0.491347,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0266391);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336429,-99) , 
4, 0.77954, 0, 0, 0.517076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177233,-99) , 
5, 1.88842, 1, 0, 0.494538,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0302552);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.788179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452427,-99) , 
13, 2.31215, 0, 0, 0.540208,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436314,-99) , 
1, 321.715, 1, 0, 0.462705,-99) , 
8, 1.95319, 1, 0, 0.489919,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0292846);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403985,-99) , 
12, 182.064, 1, 0, 0.543964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44937,-99) , 
6, 2.92529, 1, 0, 0.466153,-99) , 
8, 1.95319, 1, 0, 0.493446,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0269399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445283,-99) , 
6, 2.98307, 0, 0, 0.517893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183891,-99) , 
5, 1.88842, 1, 0, 0.496042,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0193836);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466979,-99) , 
3, 0.17288, 1, 0, 0.476176,-99) , 
13, 5.39987, 0, 0, 0.493814,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0266966);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439835,-99) , 
10, 302.187, 0, 0, 0.518418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188891,-99) , 
5, 1.88842, 1, 0, 0.496962,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0189626);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659313,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43321,-99) , 
3, 0.333511, 1, 0, 0.477129,-99) , 
13, 5.39987, 0, 0, 0.49435,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0352303);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.978714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373715,-99) , 
11, 269.663, 1, 0, 0.586335,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430215,-99) , 
13, 1.77553, 1, 0, 0.47324,-99) , 
3, 0.421876, 0, 0, 0.493359,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0197051);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438082,-99) , 
8, 2.18312, 0, 0, 0.476106,-99) , 
13, 5.39987, 0, 0, 0.49473,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0304158);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.827512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455326,-99) , 
13, 2.31215, 0, 0, 0.5483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448531,-99) , 
6, 2.92529, 1, 0, 0.465257,-99) , 
8, 1.95319, 1, 0, 0.494125,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.028117);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331727,-99) , 
4, 0.779602, 0, 0, 0.526075,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395202,-99) , 
14, 0.324177, 0, 0, 0.428375,-99) , 
12, 66.8541, 0, 0, 0.499058,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0339418);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.02501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381619,-99) , 
11, 269.663, 1, 0, 0.598907,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426441,-99) , 
1, 347.215, 0, 0, 0.474367,-99) , 
3, 0.421876, 0, 0, 0.496062,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0328539);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.0259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38966,-99) , 
11, 269.663, 1, 0, 0.60255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436175,-99) , 
13, 1.77553, 1, 0, 0.474315,-99) , 
3, 0.421876, 0, 0, 0.496523,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0210668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454138,-99) , 
6, 3.09649, 0, 0, 0.476425,-99) , 
13, 5.39987, 0, 0, 0.497847,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0208062);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715725,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440056,-99) , 
8, 2.18312, 0, 0, 0.478019,-99) , 
13, 5.39987, 0, 0, 0.498852,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0317602);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417941,-99) , 
11, 183.917, 0, 0, 0.557203,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445527,-99) , 
7, 701.572, 1, 0, 0.467286,-99) , 
8, 1.95319, 1, 0, 0.498246,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0313986);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.09298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398309,-99) , 
11, 269.663, 1, 0, 0.619642,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435551,-99) , 
1, 347.215, 0, 0, 0.476607,-99) , 
3, 0.421876, 0, 0, 0.500906,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0304638);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.945682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386909,-99) , 
11, 288.111, 1, 0, 0.623491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442173,-99) , 
13, 1.87284, 1, 0, 0.476563,-99) , 
3, 0.421876, 0, 0, 0.501382,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.021686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.762704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451479,-99) , 
12, 99.7314, 1, 0, 0.478442,-99) , 
13, 5.39987, 0, 0, 0.502125,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0306594);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398662,-99) , 
0, 1.0002, 1, 0, 0.534034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425701,-99) , 
6, 2.93257, 1, 0, 0.441766,-99) , 
12, 76.352, 0, 0, 0.502503,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0218184);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.765429,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464171,-99) , 
1, 301.05, 1, 0, 0.477984,-99) , 
13, 5.39987, 0, 0, 0.501592,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0340912);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367944,-99) , 
2, 122.521, 1, 0, 0.533181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325685,-99) , 
2, 97.1449, 0, 0, 0.424553,-99) , 
10, 302.187, 0, 0, 0.504171,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0319332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.915764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366018,-99) , 
2, 109.329, 1, 0, 0.63545,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450965,-99) , 
14, 0.288778, 0, 0, 0.473413,-99) , 
3, 0.421876, 0, 0, 0.500121,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0321934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376872,-99) , 
15, 0.00029997, 1, 0, 0.531181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332747,-99) , 
2, 97.1449, 0, 0, 0.424754,-99) , 
10, 302.187, 0, 0, 0.502688,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.022992);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461661,-99) , 
2, 117.437, 0, 0, 0.474151,-99) , 
13, 5.39987, 0, 0, 0.498928,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0314147);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.05351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383758,-99) , 
11, 288.111, 1, 0, 0.644211,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466383,-99) , 
1, 521.341, 0, 0, 0.474401,-99) , 
3, 0.421876, 0, 0, 0.501924,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0311108);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380886,-99) , 
3, 0.52005, 1, 0, 0.528938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203156,-99) , 
5, 1.88842, 1, 0, 0.508014,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0319132);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.967613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360096,-99) , 
2, 110.237, 1, 0, 0.656183,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464595,-99) , 
3, 0.17286, 1, 0, 0.474309,-99) , 
3, 0.421876, 0, 0, 0.503269,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0334017);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372342,-99) , 
2, 122.521, 1, 0, 0.537209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346289,-99) , 
2, 97.1449, 0, 0, 0.430696,-99) , 
10, 302.187, 0, 0, 0.508558,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0368329);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.840817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43441,-99) , 
0, 0.00069993, 0, 0, 0.574319,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426643,-99) , 
7, 870.478, 1, 0, 0.466154,-99) , 
11, 244.054, 1, 0, 0.504631,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0358496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399277,-99) , 
10, 282.774, 0, 0, 0.577646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455681,-99) , 
7, 702.292, 1, 0, 0.467759,-99) , 
11, 244.054, 1, 0, 0.506748,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0331614);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385008,-99) , 
15, 0.00029997, 1, 0, 0.541097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404407,-99) , 
10, 267.136, 1, 0, 0.429891,-99) , 
10, 302.187, 0, 0, 0.511035,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0261836);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.937692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437983,-99) , 
8, 2.18919, 0, 0, 0.477935,-99) , 
13, 5.39987, 0, 0, 0.50847,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0372952);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.21637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453372,-99) , 
13, 2.31215, 0, 0, 0.590627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331183,-99) , 
13, 4.50176, 1, 0, 0.46705,-99) , 
8, 1.95319, 1, 0, 0.507913,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0383974);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.736065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414405,-99) , 
14, 0.476546, 1, 0, 0.597201,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445444,-99) , 
6, 2.92529, 1, 0, 0.462516,-99) , 
8, 1.95319, 1, 0, 0.506927,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0268061);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.01657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43288,-99) , 
3, 0.333511, 1, 0, 0.477968,-99) , 
13, 5.39987, 0, 0, 0.511281,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0367311);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.2841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37724,-99) , 
2, 108.658, 1, 0, 0.72653,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451529,-99) , 
14, 0.323373, 0, 0, 0.473296,-99) , 
3, 0.421876, 0, 0, 0.510122,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0385871);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377498,-99) , 
14, 0.686752, 1, 0, 0.597427,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419887,-99) , 
6, 3.0643, 0, 0, 0.469448,-99) , 
11, 244.054, 1, 0, 0.513754,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0277305);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.10664,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463902,-99) , 
2, 117.437, 0, 0, 0.477114,-99) , 
13, 5.39987, 0, 0, 0.512705,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0367497);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372922,-99) , 
2, 122.521, 1, 0, 0.549827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353553,-99) , 
2, 97.1449, 0, 0, 0.42951,-99) , 
10, 302.187, 0, 0, 0.516593,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0370104);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.40133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375167,-99) , 
2, 109.329, 1, 0, 0.75445,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464686,-99) , 
1, 518.438, 0, 0, 0.473209,-99) , 
3, 0.421876, 0, 0, 0.512443,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0393752);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445972,-99) , 
3, 0.225189, 0, 0, 0.546893,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250767,-99) , 
3, 0.599553, 0, 0, 0.358835,-99) , 
3, 0.52005, 1, 0, 0.519841,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0423294);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.07642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434818,-99) , 
0, 0.00069993, 0, 0, 0.616692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455176,-99) , 
7, 701.358, 1, 0, 0.467739,-99) , 
11, 244.054, 1, 0, 0.518141,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0400495);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403772,-99) , 
2, 121.278, 1, 0, 0.552909,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261079,-99) , 
3, 0.599553, 0, 0, 0.363709,-99) , 
3, 0.52005, 1, 0, 0.525674,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0390766);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.229987,-99) , 
7, 1445.61, 1, 0, 0.55859,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.423961,-99) , 
10, 302.187, 0, 0, 0.520848,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0432825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378971,-99) , 
14, 0.686752, 1, 0, 0.624549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453176,-99) , 
7, 698.088, 1, 0, 0.464432,-99) , 
11, 244.054, 1, 0, 0.517817,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0449332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401366,-99) , 
12, 57.6693, 0, 0, 0.569409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393484,-99) , 
2, 108.442, 0, 0, 0.440629,-99) , 
13, 1.03694, 0, 0, 0.523213,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0431644);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.50672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337207,-99) , 
6, 3.11247, 1, 0, 0.87152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441282,-99) , 
11, 278.273, 0, 0, 0.473566,-99) , 
3, 0.421876, 0, 0, 0.521594,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0456467);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.28967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434358,-99) , 
0, 0.00069993, 0, 0, 0.639583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455221,-99) , 
7, 702.292, 1, 0, 0.467618,-99) , 
11, 244.054, 1, 0, 0.523966,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0423594);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438467,-99) , 
3, 0.205282, 0, 0, 0.562058,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278741,-99) , 
2, 101.417, 0, 0, 0.360934,-99) , 
3, 0.52005, 1, 0, 0.532551,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0431769);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379373,-99) , 
15, 0.00029997, 1, 0, 0.570176,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.42778,-99) , 
10, 302.187, 0, 0, 0.529344,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0462812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.61364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299543,-99) , 
9, 0.720741, 1, 0, 0.969676,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44969,-99) , 
14, 0.323373, 0, 0, 0.474387,-99) , 
3, 0.421876, 0, 0, 0.528049,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0589309);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.892625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455845,-99) , 
13, 2.12169, 0, 0, 0.586013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338983,-99) , 
13, 1.79101, 1, 0, 0.428832,-99) , 
14, 0.443952, 1, 0, 0.532677,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0573557);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337234,-99) , 
3, 0.513018, 1, 0, 0.592772,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35231,-99) , 
13, 1.79101, 1, 0, 0.432325,-99) , 
14, 0.443952, 1, 0, 0.538297,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0417184);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.11888,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447265,-99) , 
14, 0.323373, 0, 0, 0.47268,-99) , 
3, 0.421876, 0, 0, 0.533725,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0567945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437875,-99) , 
3, 0.240426, 0, 0, 0.595182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355887,-99) , 
13, 1.79101, 1, 0, 0.425543,-99) , 
14, 0.443952, 1, 0, 0.537117,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.05777);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.98222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371112,-99) , 
14, 0.686752, 1, 0, 0.709297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420137,-99) , 
3, 0.271146, 1, 0, 0.463708,-99) , 
11, 244.054, 1, 0, 0.538176,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0568832);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.823215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439925,-99) , 
2, 107.611, 1, 0, 0.607582,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409673,-99) , 
2, 117.143, 0, 0, 0.431957,-99) , 
13, 1.04492, 0, 0, 0.540169,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0631188);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.07391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424578,-99) , 
3, 0.248939, 0, 0, 0.677371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434663,-99) , 
3, 0.181975, 1, 0, 0.457576,-99) , 
6, 3.07096, 1, 0, 0.545084,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0565104);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44201,-99) , 
14, 0.444352, 1, 0, 0.592615,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.349937,-99) , 
3, 0.52005, 1, 0, 0.554649,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0568835);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417023,-99) , 
13, 0.727467, 0, 0, 0.611658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388962,-99) , 
3, 0.246966, 1, 0, 0.42447,-99) , 
10, 302.187, 0, 0, 0.55414,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0579524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.78038,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436184,-99) , 
14, 0.323373, 0, 0, 0.472819,-99) , 
3, 0.421876, 0, 0, 0.552776,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0630694);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.874748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459604,-99) , 
0, 0.00069993, 0, 0, 0.599059,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.347692,-99) , 
3, 0.52005, 1, 0, 0.558786,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0697492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.89901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405892,-99) , 
11, 188.09, 0, 0, 0.830747,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427412,-99) , 
3, 0.271146, 1, 0, 0.467958,-99) , 
11, 244.054, 1, 0, 0.566293,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0772865);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.896779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426858,-99) , 
3, 0.240426, 0, 0, 0.64978,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365126,-99) , 
13, 1.79101, 1, 0, 0.436324,-99) , 
14, 0.443952, 1, 0, 0.572034,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0783295);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 2.7563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444292,-99) , 
0, 0.00069993, 0, 0, 0.74105,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425523,-99) , 
6, 3.11551, 0, 0, 0.451762,-99) , 
13, 1.62558, 0, 0, 0.57576,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0804241);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.717933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350796,-99) , 
5, 0.123346, 0, 0, 0.645199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327946,-99) , 
13, 1.11565, 1, 0, 0.39073,-99) , 
15, 0.00029997, 1, 0, 0.590264,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.102865);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 2.6513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346849,-99) , 
3, 0.220052, 0, 0, 0.968843,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366976,-99) , 
3, 0.328129, 1, 0, 0.461072,-99) , 
13, 2.3195, 0, 0, 0.584039,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.092089);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.365965,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 2.61271,-99) , 
14, 0.686752, 0, 0, 1.03949,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441015,-99) , 
1, 536.117, 0, 0, 0.458741,-99) , 
11, 244.054, 1, 0, 0.588603,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0983828);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.991992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413744,-99) , 
9, 0.455943, 0, 0, 0.717575,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.404789,-99) , 
10, 302.187, 0, 0, 0.607954,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.109121);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.26152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329865,-99) , 
2, 120.981, 1, 0, 0.893081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423494,-99) , 
5, 0.225487, 1, 0, 0.450465,-99) , 
13, 1.62558, 0, 0, 0.618408,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.116679);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.2099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353766,-99) , 
3, 0.520032, 1, 0, 0.854207,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37468,-99) , 
0, 0.00059994, 1, 0, 0.446799,-99) , 
3, 0.249957, 0, 0, 0.631078,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.143373);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.343232,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 3.67999,-99) , 
13, 0.663232, 1, 0, 1.20252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415948,-99) , 
3, 0.183024, 1, 0, 0.438567,-99) , 
0, 0.00069993, 0, 0, 0.634809,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.173741);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.377144,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 2.89506,-99) , 
14, 0.479317, 0, 0, 1.05895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358844,-99) , 
13, 1.72698, 1, 0, 0.442742,-99) , 
2, 107.457, 1, 0, 0.668127,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.163646);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 3.72599,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405029,-99) , 
10, 311.721, 1, 0, 0.452228,-99) , 
13, 2.3195, 0, 0, 0.695608,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.264171);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.322212,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 1.60615,-99) , 
15, 0.00029997, 0, 0, 1.04127,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.369288,-99) , 
10, 304.094, 0, 0, 0.728138,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.429309);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 7.68304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.991032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370764,-99) , 
1, 292.17, 1, 0, 0.419102,-99) , 
6, 3.07256, 1, 0, 0.787227,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.135972);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 11.8875,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314009,-99) , 
6, 3.09301, 0, 0, 0.388546,-99) , 
3, 0.247736, 0, 0, 0.968244,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.0566036);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.358295,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.159842,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 8.99486,-99) , 
7, 1445.61, 0, 0, 2.85237,-99) , 
10, 304.094, 1, 0, 1.02785,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0389103);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209404,-99) , 
6, 3.06426, 0, 0, 0.383461,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 13.166,-99) , 
11, 296.929, 0, 0, 1.06736,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.0763113);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360863,-99) , 
14, 0.701492, 0, 0, 0.380077,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 14.0642,-99) , 
3, 0.23071, 1, 0, 1.08964,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0343649);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.352424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.354644,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 11.0267,-99) , 
5, 1.83586, 0, 0, 5.81761,-99) , 
10, 304.094, 1, 0, 1.14191,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.000544061);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296582,-99) , 
3, 0.218034, 1, 0, 0.338268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.296197,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 17.106,-99) , 
9, 0.970972, 0, 0, 4.15204,-99) , 
9, 0.456091, 1, 0, 1.1703,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.001088);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296696,-99) , 
3, 0.218034, 1, 0, 0.338339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.301035,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 17.0905,-99) , 
9, 0.968964, 0, 0, 4.16002,-99) , 
9, 0.456091, 1, 0, 1.17075,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.0032441);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296923,-99) , 
3, 0.218034, 1, 0, 0.338482,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.31233,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 15.3365,-99) , 
6, 2.7586, 1, 0, 4.17603,-99) , 
9, 0.456091, 1, 0, 1.17165,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.00228858);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2976,-99) , 
3, 0.218034, 1, 0, 0.338907,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.313027,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 16.0859,-99) , 
6, 2.7586, 1, 0, 4.2242,-99) , 
9, 0.456091, 1, 0, 1.1743,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.00161084);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298079,-99) , 
3, 0.218034, 1, 0, 0.339207,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.31352,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 16.6618,-99) , 
6, 2.7586, 1, 0, 4.25895,-99) , 
9, 0.456091, 1, 0, 1.17619,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.00113198);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298416,-99) , 
3, 0.218034, 1, 0, 0.339418,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.313866,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 17.0934,-99) , 
6, 2.7586, 1, 0, 4.28379,-99) , 
9, 0.456091, 1, 0, 1.17752,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.00126895);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298653,-99) , 
3, 0.218034, 1, 0, 0.339566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.316473,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 17.0172,-99) , 
6, 2.75988, 1, 0, 4.30145,-99) , 
9, 0.456091, 1, 0, 1.17846,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.00112162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298919,-99) , 
3, 0.218034, 1, 0, 0.339733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.317569,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 17.079,-99) , 
6, 2.75629, 1, 0, 4.3214,-99) , 
9, 0.456091, 1, 0, 1.17951,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.00207049);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299154,-99) , 
3, 0.218034, 1, 0, 0.33988,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.324287,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 16.3343,-99) , 
6, 2.75597, 1, 0, 4.3392,-99) , 
9, 0.456091, 1, 0, 1.18044,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.0248346);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317425,-99) , 
3, 0.219015, 1, 0, 0.357675,-99) , 
NN(
0, 
0, 
1, 286.468, 1, 1, 8.04536,-99) , 
10, 304.094, 1, 0, 1.18216,-99)    );
  // itree = 173
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294403,-99) , 
3, 0.218034, 1, 0, 0.334601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.3195,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 11.2448,-99) , 
5, 1.83672, 0, 0, 4.97436,-99) , 
9, 0.456091, 1, 0, 1.20099,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_singleClass_boosted_boosted_2017::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_singleClass_boosted_boosted_2017::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
