// Class: ReadBDT_singleClass_boosted_boosted_2017
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_singleClass_boosted_boosted_2017
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : ceballos
Date           : Sun May 27 15:40:38 2018
Host           : Linux cmsbuild20.cern.ch 2.6.32-696.23.1.el6.x86_64 #1 SMP Wed Mar 14 11:28:37 CET 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ceballos/cms/cmssw/048/CMSSW_9_4_6/src
Training events: 9540
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "400" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "10000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "1.000000e-01" [Learning rate  for AdaBoost algorithm]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
SeparationType: "misclassificationerror" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
nIsojet                       nIsojet                       nIsojet                       nIsojet                                                         'F'    [0,7]
fjPt                          fjPt                          fjPt                          fjPt                                                            'F'    [250.05796814,1592.09289551]
MSD                           MSD                           MSD                           MSD                                                             'F'    [80.0121459961,149.853881836]
Tau21SD                       Tau21SD                       Tau21SD                       Tau21SD                                                         'F'    [0.0746132731438,1]
ptBalanceZHFJ                 ptBalanceZHFJ                 ptBalanceZHFJ                 ptBalanceZHFJ                                                   'F'    [0.455623656511,4.66275644302]
dEtaZHFJ                      dEtaZHFJ                      dEtaZHFJ                      dEtaZHFJ                                                        'F'    [0.000291109085083,4.27346277237]
dPhiZHFJ                      dPhiZHFJ                      dPhiZHFJ                      dPhiZHFJ                                                        'F'    [2.50001072884,3.14159107208]
mTZHFJ                        mTZHFJ                        mTZHFJ                        mTZHFJ                                                          'F'    [537.972839355,5224.61816406]
ptBalanceL1L2                 ptBalanceL1L2                 ptBalanceL1L2                 ptBalanceL1L2                                                   'F'    [0.158768773079,61.4080543518]
dRL1L2                        dRL1L2                        dRL1L2                        dRL1L2                                                          'F'    [0.141968935728,2.1290268898]
ZBosonPt                      ZBosonPt                      ZBosonPt                      ZBosonPt                                                        'F'    [250.03062439,1371.78540039]
lepton1Pt                     lepton1Pt                     lepton1Pt                     lepton1Pt                                                       'F'    [43.154460907,1290.32702637]
lepton2Pt                     lepton2Pt                     lepton2Pt                     lepton2Pt                                                       'F'    [10.0233974457,531.937011719]
deltaM                        deltaM                        deltaM                        deltaM                                                          'F'    [4.6594239393e-05,15.9538431168]
CosThetaCS                    CosThetaCS                    CosThetaCS                    CosThetaCS                                                      'F'    [-0.999999523163,0.999855995178]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_singleClass_boosted_boosted_2017Node
   
#ifndef BDT_singleClass_boosted_boosted_2017Node__def
#define BDT_singleClass_boosted_boosted_2017Node__def
   
class BDT_singleClass_boosted_boosted_2017Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_singleClass_boosted_boosted_2017Node ( BDT_singleClass_boosted_boosted_2017Node* left,BDT_singleClass_boosted_boosted_2017Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_singleClass_boosted_boosted_2017Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_singleClass_boosted_boosted_2017Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_singleClass_boosted_boosted_2017Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_singleClass_boosted_boosted_2017Node*   fLeft;     // pointer to the left daughter node
   BDT_singleClass_boosted_boosted_2017Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_singleClass_boosted_boosted_2017Node::~BDT_singleClass_boosted_boosted_2017Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_singleClass_boosted_boosted_2017Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_singleClass_boosted_boosted_2017Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_singleClass_boosted_boosted_2017 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_singleClass_boosted_boosted_2017( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_singleClass_boosted_boosted_2017" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "nIsojet", "fjPt", "MSD", "Tau21SD", "ptBalanceZHFJ", "dEtaZHFJ", "dPhiZHFJ", "mTZHFJ", "ptBalanceL1L2", "dRL1L2", "ZBosonPt", "lepton1Pt", "lepton2Pt", "deltaM", "CosThetaCS" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_singleClass_boosted_boosted_2017() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_singleClass_boosted_boosted_2017Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_singleClass_boosted_boosted_2017::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_singleClass_boosted_boosted_2017Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_singleClass_boosted_boosted_2017Node*)current->GetRight();
         else current=(BDT_singleClass_boosted_boosted_2017Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_singleClass_boosted_boosted_2017::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.084998314016188);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360563,-99) , 
6, 2.86855, 0, 0, 0.641777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239538,-99) , 
9, 0.530975, 1, 0, 0.323485,-99) , 
2, 100.243, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.0763238);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378298,-99) , 
6, 2.86907, 0, 0, 0.639073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268929,-99) , 
9, 0.530975, 1, 0, 0.344571,-99) , 
2, 102.094, 0, 0, 0.496796,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.0733094);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343979,-99) , 
12, 46.5205, 0, 0, 0.648431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315742,-99) , 
12, 144.047, 0, 0, 0.369483,-99) , 
2, 105.125, 0, 0, 0.494432,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0680764);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35593,-99) , 
7, 1171.17, 1, 0, 0.611297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282475,-99) , 
9, 0.530975, 1, 0, 0.347893,-99) , 
2, 100.243, 0, 0, 0.494395,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0658775);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388516,-99) , 
5, 1.12669, 1, 0, 0.626713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293497,-99) , 
4, 0.920045, 1, 0, 0.382155,-99) , 
2, 105.125, 0, 0, 0.491514,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0602983);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436535,-99) , 
6, 3.00969, 0, 0, 0.603022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278882,-99) , 
4, 0.920045, 1, 0, 0.368708,-99) , 
2, 102.094, 0, 0, 0.489783,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0591288);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295855,-99) , 
9, 0.839814, 1, 0, 0.592315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319196,-99) , 
12, 144.047, 0, 0, 0.359665,-99) , 
2, 100.243, 0, 0, 0.489193,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0649844);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.24081,-99) , 
9, 0.839858, 1, 0, 0.580432,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315768,-99) , 
6, 3.12286, 0, 0, 0.344761,-99) , 
3, 0.343596, 1, 0, 0.486692,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0589753);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319073,-99) , 
3, 0.468696, 1, 0, 0.612445,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342205,-99) , 
7, 702.196, 1, 0, 0.398976,-99) , 
2, 107.01, 0, 0, 0.484208,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0643773);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389235,-99) , 
8, 4.1457, 1, 0, 0.569727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3093,-99) , 
8, 1.36994, 1, 0, 0.354605,-99) , 
5, 0.795449, 1, 0, 0.483925,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0540108);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304483,-99) , 
2, 131.101, 1, 0, 0.594839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325942,-99) , 
3, 0.273915, 1, 0, 0.395977,-99) , 
2, 105.125, 0, 0, 0.484518,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0518364);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412465,-99) , 
5, 0.935404, 1, 0, 0.596345,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359935,-99) , 
7, 701.598, 1, 0, 0.406737,-99) , 
2, 107.01, 0, 0, 0.482122,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0575778);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370006,-99) , 
0, 1.0002, 1, 0, 0.562041,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292292,-99) , 
4, 0.859952, 1, 0, 0.358001,-99) , 
2, 98.0295, 0, 0, 0.483715,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0540429);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250174,-99) , 
9, 0.839277, 1, 0, 0.558926,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347942,-99) , 
6, 3.12286, 0, 0, 0.37333,-99) , 
3, 0.333511, 1, 0, 0.481392,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0572772);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356712,-99) , 
4, 1.14847, 1, 0, 0.554055,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325767,-99) , 
8, 1.36994, 1, 0, 0.367565,-99) , 
5, 0.795449, 1, 0, 0.479689,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0456943);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307095,-99) , 
2, 131.099, 1, 0, 0.582561,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372415,-99) , 
7, 701.598, 1, 0, 0.410721,-99) , 
2, 107.01, 0, 0, 0.479007,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0508749);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313266,-99) , 
3, 0.514498, 1, 0, 0.553184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347737,-99) , 
3, 0.192579, 1, 0, 0.379643,-99) , 
8, 2.96983, 1, 0, 0.478713,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0432215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381705,-99) , 
5, 1.12375, 1, 0, 0.573987,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370069,-99) , 
9, 0.530975, 1, 0, 0.414228,-99) , 
2, 107.01, 0, 0, 0.477547,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0508417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44474,-99) , 
0, 0.00069993, 1, 0, 0.543008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298655,-99) , 
9, 0.542697, 1, 0, 0.363959,-99) , 
2, 97.5058, 0, 0, 0.477535,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.04744);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349222,-99) , 
3, 0.467863, 1, 0, 0.543936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310766,-99) , 
4, 0.859952, 1, 0, 0.369127,-99) , 
2, 97.5058, 0, 0, 0.480145,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0495544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400305,-99) , 
8, 4.1457, 1, 0, 0.540694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343292,-99) , 
8, 1.37521, 1, 0, 0.380998,-99) , 
5, 0.795449, 1, 0, 0.477191,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0405843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305447,-99) , 
2, 131.099, 1, 0, 0.562637,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382448,-99) , 
14, 0.324575, 0, 0, 0.421836,-99) , 
2, 107.01, 0, 0, 0.477664,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0436332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31011,-99) , 
5, 1.29963, 1, 0, 0.53919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370896,-99) , 
6, 3.12286, 0, 0, 0.390816,-99) , 
3, 0.333511, 1, 0, 0.477194,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0459469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397977,-99) , 
13, 0.975206, 0, 0, 0.558568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401326,-99) , 
3, 0.192532, 1, 0, 0.428154,-99) , 
8, 1.95319, 1, 0, 0.47616,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0467406);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445169,-99) , 
0, 0.00069993, 1, 0, 0.533812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298882,-99) , 
9, 0.542697, 1, 0, 0.363386,-99) , 
2, 95.5364, 0, 0, 0.480378,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0435704);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35069,-99) , 
3, 0.467863, 1, 0, 0.53477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311537,-99) , 
4, 0.859952, 1, 0, 0.368139,-99) , 
2, 95.5364, 0, 0, 0.482645,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0440472);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4236,-99) , 
3, 0.334996, 1, 0, 0.571568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368113,-99) , 
5, 0.515398, 1, 0, 0.437534,-99) , 
14, 0.323373, 0, 0, 0.479391,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0403821);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404661,-99) , 
3, 0.400895, 1, 0, 0.571051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359021,-99) , 
7, 836.014, 1, 0, 0.439287,-99) , 
14, 0.323373, 0, 0, 0.480375,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0381806);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438028,-99) , 
3, 0.334996, 1, 0, 0.567677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407433,-99) , 
14, -0.717783, 1, 0, 0.43944,-99) , 
14, 0.323373, 0, 0, 0.479377,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0411907);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40973,-99) , 
2, 122.916, 1, 0, 0.547915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284034,-99) , 
4, 1.01007, 1, 0, 0.429898,-99) , 
2, 105.125, 0, 0, 0.482522,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0380302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394969,-99) , 
2, 93.5738, 0, 0, 0.565188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381626,-99) , 
5, 0.515398, 1, 0, 0.440806,-99) , 
14, 0.323373, 0, 0, 0.479384,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0361219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420812,-99) , 
2, 122.519, 1, 0, 0.548433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417441,-99) , 
13, 5.42309, 0, 0, 0.433402,-99) , 
2, 107.01, 0, 0, 0.479188,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0393603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381023,-99) , 
5, 1.12616, 1, 0, 0.535765,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373907,-99) , 
6, 3.12079, 0, 0, 0.400542,-99) , 
8, 3.2148, 1, 0, 0.48225,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.035048);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364634,-99) , 
3, 0.472933, 1, 0, 0.562959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376099,-99) , 
7, 833.671, 1, 0, 0.444818,-99) , 
14, 0.323373, 0, 0, 0.481456,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0384737);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402655,-99) , 
13, 0.974102, 0, 0, 0.574062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.669425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429561,-99) , 
3, 0.17287, 1, 0, 0.448565,-99) , 
12, 140.802, 0, 0, 0.47998,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0400183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453957,-99) , 
0, 0.00069993, 1, 0, 0.528869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331442,-99) , 
9, 0.538922, 1, 0, 0.388365,-99) , 
2, 95.5364, 0, 0, 0.485344,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0340989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398948,-99) , 
5, 1.12616, 1, 0, 0.534139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387478,-99) , 
2, 115.057, 0, 0, 0.415954,-99) , 
8, 3.2148, 1, 0, 0.487401,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0328803);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412787,-99) , 
2, 93.5738, 0, 0, 0.562396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417565,-99) , 
2, 111.089, 0, 0, 0.452058,-99) , 
14, 0.323373, 0, 0, 0.486422,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0327425);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419732,-99) , 
6, 2.98365, 0, 0, 0.530396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399589,-99) , 
6, 3.12079, 0, 0, 0.421995,-99) , 
8, 3.2148, 1, 0, 0.487563,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0324676);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375539,-99) , 
3, 0.472933, 1, 0, 0.55813,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390473,-99) , 
7, 836.014, 1, 0, 0.455602,-99) , 
14, 0.323373, 0, 0, 0.487545,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0353532);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362876,-99) , 
3, 0.484426, 1, 0, 0.52457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346821,-99) , 
9, 0.538922, 1, 0, 0.399821,-99) , 
2, 95.5364, 0, 0, 0.486142,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0308107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362684,-99) , 
2, 122.629, 1, 0, 0.551167,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426539,-99) , 
14, -0.717783, 1, 0, 0.452692,-99) , 
14, 0.323373, 0, 0, 0.483299,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0402623);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370436,-99) , 
5, 1.12616, 1, 0, 0.524477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383307,-99) , 
12, 141.608, 0, 0, 0.41798,-99) , 
4, 1.04919, 1, 0, 0.484563,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0331036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419343,-99) , 
2, 122.519, 1, 0, 0.539487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429978,-99) , 
13, 5.42309, 0, 0, 0.447307,-99) , 
2, 107.01, 0, 0, 0.483997,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.034763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400887,-99) , 
13, 0.975206, 0, 0, 0.543558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43029,-99) , 
7, 701.572, 1, 0, 0.454165,-99) , 
8, 1.95319, 1, 0, 0.486918,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0304826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30679,-99) , 
4, 0.779602, 0, 0, 0.523148,-99) , 
NN(
0, 
0, 
0, 0.00059994, 1, -1, 0.397261,-99) , 
12, 66.3322, 0, 0, 0.489507,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0298748);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408915,-99) , 
14, 0.866615, 1, 0, 0.549819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401454,-99) , 
7, 833.671, 1, 0, 0.459003,-99) , 
14, 0.323373, 0, 0, 0.487161,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0372555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385553,-99) , 
1, 327.973, 0, 0, 0.534153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315366,-99) , 
4, 1.01007, 1, 0, 0.447867,-99) , 
2, 105.125, 0, 0, 0.486357,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0288229);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441476,-99) , 
3, 0.334996, 1, 0, 0.543307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412461,-99) , 
5, 0.515398, 1, 0, 0.456063,-99) , 
14, 0.323373, 0, 0, 0.483089,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0332271);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40324,-99) , 
13, 1.19222, 0, 0, 0.558746,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441024,-99) , 
3, 0.192584, 1, 0, 0.461693,-99) , 
12, 143.776, 0, 0, 0.483818,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0342958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420763,-99) , 
2, 122.496, 1, 0, 0.533836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32942,-99) , 
4, 1.01049, 1, 0, 0.451516,-99) , 
2, 105.125, 0, 0, 0.488259,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0282433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435839,-99) , 
14, 0.801752, 1, 0, 0.546198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435451,-99) , 
14, -0.717783, 1, 0, 0.458814,-99) , 
14, 0.323373, 0, 0, 0.485808,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0326399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39372,-99) , 
1, 327.973, 0, 0, 0.533069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335629,-99) , 
4, 1.01385, 1, 0, 0.451589,-99) , 
2, 105.125, 0, 0, 0.487959,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0315812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453203,-99) , 
11, 266.875, 1, 0, 0.528981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387145,-99) , 
7, 769.8, 1, 0, 0.449554,-99) , 
2, 105.125, 0, 0, 0.485002,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0307918);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400772,-99) , 
2, 125.188, 1, 0, 0.530181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431628,-99) , 
13, 5.40085, 0, 0, 0.450316,-99) , 
2, 105.125, 0, 0, 0.485955,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.026831);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399774,-99) , 
10, 296.036, 0, 0, 0.545097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419964,-99) , 
7, 800.867, 1, 0, 0.462056,-99) , 
14, 0.323373, 0, 0, 0.487631,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0312496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.732644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42349,-99) , 
12, 181.515, 1, 0, 0.560728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45025,-99) , 
3, 0.17287, 1, 0, 0.46583,-99) , 
12, 143.776, 0, 0, 0.487264,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0291687);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308094,-99) , 
4, 0.779602, 0, 0, 0.523038,-99) , 
NN(
0, 
0, 
0, 0.00059994, 1, -1, 0.410027,-99) , 
12, 66.3322, 0, 0, 0.492547,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0347876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398519,-99) , 
6, 2.98307, 0, 0, 0.520212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283915,-99) , 
2, 97.1449, 0, 0, 0.4031,-99) , 
10, 302.187, 0, 0, 0.490359,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0271468);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431431,-99) , 
14, 0.801752, 1, 0, 0.541334,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397005,-99) , 
4, 1.02984, 1, 0, 0.463306,-99) , 
14, 0.323373, 0, 0, 0.487344,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0288087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.831826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400226,-99) , 
12, 76.1545, 0, 0, 0.612573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441049,-99) , 
2, 111.089, 0, 0, 0.470692,-99) , 
13, 5.39987, 0, 0, 0.48637,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0316153);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404272,-99) , 
13, 0.975206, 0, 0, 0.537006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404014,-99) , 
6, 3.06259, 0, 0, 0.461985,-99) , 
8, 1.95319, 1, 0, 0.488989,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0303356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411909,-99) , 
13, 0.975206, 0, 0, 0.535497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363579,-99) , 
5, 0.914658, 1, 0, 0.461996,-99) , 
8, 1.95319, 1, 0, 0.488424,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0266587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.856161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404008,-99) , 
2, 111.784, 1, 0, 0.613628,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444601,-99) , 
6, 3.10355, 0, 0, 0.47088,-99) , 
13, 5.39987, 0, 0, 0.486403,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.029036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454446,-99) , 
13, 2.31215, 0, 0, 0.53719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445972,-99) , 
6, 2.92529, 1, 0, 0.461645,-99) , 
8, 1.95319, 1, 0, 0.488755,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0324271);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462588,-99) , 
11, 268.745, 1, 0, 0.52259,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295894,-99) , 
2, 97.1449, 0, 0, 0.408137,-99) , 
10, 302.187, 0, 0, 0.493263,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0310877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419174,-99) , 
6, 2.98307, 0, 0, 0.524908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302694,-99) , 
2, 97.1449, 0, 0, 0.407688,-99) , 
10, 302.187, 0, 0, 0.494901,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0296462);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326977,-99) , 
4, 0.780788, 0, 0, 0.521396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381134,-99) , 
2, 111.786, 0, 0, 0.407255,-99) , 
10, 302.187, 0, 0, 0.492199,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0234371);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.780809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463923,-99) , 
5, 0.370053, 0, 0, 0.627253,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416208,-99) , 
3, 0.333511, 1, 0, 0.472846,-99) , 
13, 5.39987, 0, 0, 0.4892,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0229819);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46588,-99) , 
10, 341.973, 0, 0, 0.627557,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460134,-99) , 
3, 0.17288, 1, 0, 0.472073,-99) , 
13, 5.39987, 0, 0, 0.488502,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0281042);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436045,-99) , 
10, 302.187, 0, 0, 0.517427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.156033,-99) , 
5, 1.88842, 1, 0, 0.492739,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0293862);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34404,-99) , 
2, 122.49, 1, 0, 0.545175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42065,-99) , 
7, 800.867, 1, 0, 0.465517,-99) , 
14, 0.323373, 0, 0, 0.489957,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0233331);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.808947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461558,-99) , 
5, 0.370053, 0, 0, 0.635377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450492,-99) , 
2, 112.499, 0, 0, 0.472521,-99) , 
13, 5.39987, 0, 0, 0.489397,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0266562);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38291,-99) , 
3, 0.520328, 1, 0, 0.515592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162321,-99) , 
5, 1.88842, 1, 0, 0.491779,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0228934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.813955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462289,-99) , 
5, 0.370053, 0, 0, 0.635765,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459995,-99) , 
3, 0.17288, 1, 0, 0.470728,-99) , 
13, 5.39987, 0, 0, 0.487639,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0299168);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418893,-99) , 
11, 183.431, 0, 0, 0.542322,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435857,-99) , 
1, 321.715, 1, 0, 0.464193,-99) , 
8, 1.95319, 1, 0, 0.49186,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0269379);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335908,-99) , 
4, 0.77954, 0, 0, 0.51688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167506,-99) , 
5, 1.88842, 1, 0, 0.49344,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0224572);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469542,-99) , 
11, 303.893, 1, 0, 0.643167,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448939,-99) , 
6, 3.10355, 0, 0, 0.471509,-99) , 
13, 5.39987, 0, 0, 0.488775,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0216598);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46971,-99) , 
10, 332.726, 0, 0, 0.643722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459487,-99) , 
2, 117.437, 0, 0, 0.473702,-99) , 
13, 5.39987, 0, 0, 0.490758,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0267269);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439043,-99) , 
10, 302.187, 0, 0, 0.516804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.17316,-99) , 
5, 1.88842, 1, 0, 0.493917,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0202249);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646668,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438817,-99) , 
0, 0.00069993, 1, 0, 0.47418,-99) , 
13, 5.39987, 0, 0, 0.491286,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0300746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.784764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453845,-99) , 
13, 2.31215, 0, 0, 0.541314,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442642,-99) , 
7, 701.572, 1, 0, 0.463865,-99) , 
8, 1.95319, 1, 0, 0.491105,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0262922);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379521,-99) , 
5, 0.102237, 0, 0, 0.517612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179526,-99) , 
5, 1.88842, 1, 0, 0.495283,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0201792);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651328,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464042,-99) , 
3, 0.17288, 1, 0, 0.473854,-99) , 
13, 5.39987, 0, 0, 0.491077,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0298375);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40341,-99) , 
12, 182.064, 1, 0, 0.545032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330666,-99) , 
13, 4.50176, 1, 0, 0.46694,-99) , 
8, 1.95319, 1, 0, 0.494332,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.033961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.800039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417068,-99) , 
12, 181.515, 1, 0, 0.572283,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432222,-99) , 
1, 321.715, 1, 0, 0.469189,-99) , 
12, 143.776, 0, 0, 0.491113,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0200976);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45726,-99) , 
2, 112.499, 0, 0, 0.475197,-99) , 
13, 5.39987, 0, 0, 0.493772,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0299259);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417427,-99) , 
11, 183.917, 0, 0, 0.547483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450203,-99) , 
6, 2.92529, 1, 0, 0.467426,-99) , 
8, 1.95319, 1, 0, 0.495362,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0271126);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448356,-99) , 
6, 2.98307, 0, 0, 0.520211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.186283,-99) , 
5, 1.88842, 1, 0, 0.498368,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0198068);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432896,-99) , 
3, 0.333511, 1, 0, 0.47707,-99) , 
13, 5.39987, 0, 0, 0.496139,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0194806);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678531,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467727,-99) , 
3, 0.17288, 1, 0, 0.47643,-99) , 
13, 5.39987, 0, 0, 0.49511,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0270897);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440914,-99) , 
10, 302.187, 0, 0, 0.519861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190361,-99) , 
5, 1.88842, 1, 0, 0.498302,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0357582);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.03873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37541,-99) , 
11, 269.663, 1, 0, 0.600057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431193,-99) , 
13, 1.77553, 1, 0, 0.473559,-99) , 
3, 0.421876, 0, 0, 0.495674,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0206582);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701626,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43831,-99) , 
8, 2.18312, 0, 0, 0.476937,-99) , 
13, 5.39987, 0, 0, 0.497103,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.031162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.858938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455344,-99) , 
13, 2.31215, 0, 0, 0.553495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449233,-99) , 
6, 2.92529, 1, 0, 0.466382,-99) , 
8, 1.95319, 1, 0, 0.496486,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0300106);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400804,-99) , 
0, 1.0002, 1, 0, 0.531784,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423265,-99) , 
10, 412.386, 0, 0, 0.441624,-99) , 
12, 75.6736, 0, 0, 0.501588,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0270853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343632,-99) , 
4, 0.77954, 0, 0, 0.52141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198351,-99) , 
5, 1.88842, 1, 0, 0.500554,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0351822);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.11145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380539,-99) , 
11, 269.663, 1, 0, 0.614104,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423438,-99) , 
1, 347.215, 0, 0, 0.471586,-99) , 
3, 0.421876, 0, 0, 0.495853,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0337729);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.11591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388867,-99) , 
11, 269.663, 1, 0, 0.61843,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434247,-99) , 
13, 1.77553, 1, 0, 0.471538,-99) , 
3, 0.421876, 0, 0, 0.496383,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0220917);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.757051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435842,-99) , 
8, 2.18919, 0, 0, 0.474238,-99) , 
13, 5.39987, 0, 0, 0.497789,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0216234);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752965,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461476,-99) , 
1, 301.05, 1, 0, 0.474067,-99) , 
13, 5.39987, 0, 0, 0.497188,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0324512);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.1681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396361,-99) , 
11, 269.663, 1, 0, 0.630776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45068,-99) , 
14, 0.288778, 0, 0, 0.473511,-99) , 
3, 0.421876, 0, 0, 0.499732,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0334825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366134,-99) , 
2, 122.521, 1, 0, 0.53086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32716,-99) , 
2, 97.1449, 0, 0, 0.42564,-99) , 
10, 302.187, 0, 0, 0.502825,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0324386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.00896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379906,-99) , 
11, 288.111, 1, 0, 0.634288,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430452,-99) , 
1, 347.215, 0, 0, 0.472162,-99) , 
3, 0.421876, 0, 0, 0.498831,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0225477);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792911,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466111,-99) , 
3, 0.17288, 1, 0, 0.474241,-99) , 
13, 5.39987, 0, 0, 0.499075,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.032492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.929048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358261,-99) , 
2, 110.237, 1, 0, 0.646627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439727,-99) , 
13, 1.87284, 1, 0, 0.47501,-99) , 
3, 0.421876, 0, 0, 0.502932,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0228972);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.818747,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455821,-99) , 
6, 3.09649, 0, 0, 0.47763,-99) , 
13, 5.39987, 0, 0, 0.503507,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0357801);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.813224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434572,-99) , 
0, 0.00069993, 0, 0, 0.569353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429105,-99) , 
7, 870.478, 1, 0, 0.468422,-99) , 
11, 244.054, 1, 0, 0.504719,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0343286);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.0574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455814,-99) , 
13, 2.31215, 0, 0, 0.579011,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339809,-99) , 
13, 4.50176, 1, 0, 0.470082,-99) , 
8, 1.95319, 1, 0, 0.506687,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0347198);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406028,-99) , 
14, 0.647917, 1, 0, 0.584511,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435523,-99) , 
14, -0.312367, 1, 0, 0.465851,-99) , 
8, 1.95319, 1, 0, 0.505638,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0347253);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.935497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450686,-99) , 
6, 3.05568, 1, 0, 0.582257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448567,-99) , 
7, 701.572, 1, 0, 0.468965,-99) , 
8, 1.95319, 1, 0, 0.506868,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0354875);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379196,-99) , 
2, 122.521, 1, 0, 0.544027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333883,-99) , 
2, 97.1449, 0, 0, 0.424964,-99) , 
10, 302.187, 0, 0, 0.511744,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0342811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.10677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377544,-99) , 
2, 108.658, 1, 0, 0.690898,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453132,-99) , 
14, 0.323373, 0, 0, 0.474533,-99) , 
3, 0.421876, 0, 0, 0.507606,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0333081);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241144,-99) , 
7, 1445.61, 1, 0, 0.542655,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384738,-99) , 
6, 3.00365, 1, 0, 0.425492,-99) , 
10, 302.187, 0, 0, 0.510786,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0271703);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.98122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460457,-99) , 
2, 117.437, 0, 0, 0.474074,-99) , 
13, 5.39987, 0, 0, 0.506458,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0369303);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402431,-99) , 
10, 282.774, 0, 0, 0.58844,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45519,-99) , 
1, 527.799, 0, 0, 0.467828,-99) , 
11, 244.054, 1, 0, 0.510171,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0382274);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366973,-99) , 
2, 120.981, 1, 0, 0.550967,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403008,-99) , 
2, 108.442, 0, 0, 0.445608,-99) , 
13, 1.03694, 0, 0, 0.514478,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0353458);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.19083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369454,-99) , 
2, 110.237, 1, 0, 0.727332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466307,-99) , 
1, 518.438, 0, 0, 0.475333,-99) , 
3, 0.421876, 0, 0, 0.51191,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0363596);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401409,-99) , 
2, 122.521, 1, 0, 0.545134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.251187,-99) , 
3, 0.599553, 0, 0, 0.359107,-99) , 
3, 0.52005, 1, 0, 0.518783,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0290393);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.14798,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447766,-99) , 
12, 99.5226, 1, 0, 0.477732,-99) , 
13, 5.39987, 0, 0, 0.513996,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.037699);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398017,-99) , 
0, 1.0002, 1, 0, 0.555834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422639,-99) , 
6, 2.93257, 1, 0, 0.439865,-99) , 
12, 76.352, 0, 0, 0.514842,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0289908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.18816,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462998,-99) , 
2, 117.437, 0, 0, 0.477398,-99) , 
13, 5.39987, 0, 0, 0.514074,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0367618);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449506,-99) , 
3, 0.225189, 0, 0, 0.544234,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.259569,-99) , 
3, 0.599553, 0, 0, 0.361365,-99) , 
3, 0.52005, 1, 0, 0.518205,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0386978);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.45426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367271,-99) , 
2, 110.237, 1, 0, 0.779601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44171,-99) , 
13, 1.77553, 1, 0, 0.475699,-99) , 
3, 0.421876, 0, 0, 0.516555,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0398995);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404689,-99) , 
12, 57.6693, 0, 0, 0.560528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365386,-99) , 
2, 100.069, 0, 0, 0.440856,-99) , 
13, 1.04492, 0, 0, 0.517997,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0379798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.24404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338942,-99) , 
6, 3.11247, 1, 0, 0.797194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46457,-99) , 
1, 518.438, 0, 0, 0.472885,-99) , 
3, 0.421876, 0, 0, 0.515091,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0397498);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444506,-99) , 
14, 0.444352, 1, 0, 0.551406,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.350708,-99) , 
3, 0.52005, 1, 0, 0.522449,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0457158);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.18761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429029,-99) , 
0, 0.00069993, 0, 0, 0.628138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45407,-99) , 
7, 702.292, 1, 0, 0.468019,-99) , 
11, 244.054, 1, 0, 0.521292,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0421416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232555,-99) , 
7, 1445.61, 1, 0, 0.569162,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346336,-99) , 
2, 97.1449, 0, 0, 0.42883,-99) , 
10, 302.187, 0, 0, 0.529612,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0434047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.33521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305182,-99) , 
9, 0.720741, 1, 0, 0.877873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449805,-99) , 
14, 0.323373, 0, 0, 0.475457,-99) , 
3, 0.421876, 0, 0, 0.523319,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0425401);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442714,-99) , 
14, 0.444352, 1, 0, 0.557376,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.351884,-99) , 
3, 0.52005, 1, 0, 0.527347,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0442972);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.718079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445415,-99) , 
2, 107.611, 1, 0, 0.575777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419098,-99) , 
6, 3.1123, 0, 0, 0.439845,-99) , 
13, 1.04492, 0, 0, 0.526276,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0452693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.55275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31644,-99) , 
9, 0.720741, 1, 0, 0.955153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450609,-99) , 
14, 0.323373, 0, 0, 0.476421,-99) , 
3, 0.421876, 0, 0, 0.529051,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0452441);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442576,-99) , 
14, 0.444352, 1, 0, 0.564537,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.354595,-99) , 
3, 0.52005, 1, 0, 0.533476,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0505476);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.62264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430795,-99) , 
0, 0.00069993, 0, 0, 0.66953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45556,-99) , 
7, 698.088, 1, 0, 0.469058,-99) , 
11, 244.054, 1, 0, 0.532514,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0483428);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346213,-99) , 
4, 0.780788, 0, 0, 0.590564,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.425342,-99) , 
10, 302.187, 0, 0, 0.542518,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0479475);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378015,-99) , 
2, 121.281, 1, 0, 0.595712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429493,-99) , 
9, 0.708393, 0, 0, 0.446083,-99) , 
13, 1.03694, 0, 0, 0.540256,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0433444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.17275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448325,-99) , 
14, 0.323373, 0, 0, 0.476018,-99) , 
3, 0.421876, 0, 0, 0.539226,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0501763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442375,-99) , 
14, 0.444352, 1, 0, 0.576551,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.353242,-99) , 
3, 0.52005, 1, 0, 0.542735,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.056654);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.00909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368711,-99) , 
14, 0.686752, 1, 0, 0.715282,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454032,-99) , 
7, 698.088, 1, 0, 0.4671,-99) , 
11, 244.054, 1, 0, 0.542019,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0534333);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244834,-99) , 
7, 1445.61, 1, 0, 0.605733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404214,-99) , 
2, 113.558, 0, 0, 0.421406,-99) , 
10, 302.187, 0, 0, 0.550529,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0513407);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.47457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440507,-99) , 
14, 0.323373, 0, 0, 0.473005,-99) , 
3, 0.421876, 0, 0, 0.545799,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0774142);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 2.51195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392187,-99) , 
2, 107.471, 1, 0, 0.746024,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380626,-99) , 
3, 0.328129, 1, 0, 0.466507,-99) , 
13, 2.31471, 0, 0, 0.550506,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0730007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.82961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390738,-99) , 
3, 0.249939, 0, 0, 0.767727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43757,-99) , 
2, 116.159, 0, 0, 0.465463,-99) , 
13, 2.31471, 0, 0, 0.554578,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0612155);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.878421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466089,-99) , 
0, 0.00069993, 0, 0, 0.605197,-99) , 
NN(
0, 
0, 
1, 348.066, 0, -1, 0.360601,-99) , 
3, 0.52005, 1, 0, 0.566358,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0629853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.776906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434443,-99) , 
9, 0.455943, 0, 0, 0.637859,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.432479,-99) , 
10, 302.187, 0, 0, 0.573643,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0756464);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.56947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365661,-99) , 
14, 0.686752, 1, 0, 0.877189,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430206,-99) , 
3, 0.271146, 1, 0, 0.471745,-99) , 
11, 244.054, 1, 0, 0.577273,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0791115);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.954697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416442,-99) , 
14, 0.444227, 1, 0, 0.697323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374952,-99) , 
0, 0.00059994, 1, 0, 0.443683,-99) , 
3, 0.241721, 0, 0, 0.582241,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0791392);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.70258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44911,-99) , 
0, 0.00069993, 0, 0, 0.700863,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412449,-99) , 
14, 0.42607, 0, 0, 0.445229,-99) , 
3, 0.241721, 0, 0, 0.583876,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0769876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.880055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454861,-99) , 
3, 0.241712, 0, 0, 0.643424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287815,-99) , 
2, 101.417, 0, 0, 0.36653,-99) , 
3, 0.52005, 1, 0, 0.596259,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0977655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.374696,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 3.42785,-99) , 
14, 0.458949, 0, 0, 1.03472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399955,-99) , 
3, 0.309261, 1, 0, 0.468513,-99) , 
13, 2.31471, 0, 0, 0.600333,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0963657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.22908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393152,-99) , 
6, 3.11164, 1, 0, 0.79937,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370954,-99) , 
13, 2.64407, 1, 0, 0.452211,-99) , 
2, 107.457, 1, 0, 0.60686,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.113085);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.265976,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 2.08372,-99) , 
9, 0.842648, 0, 0, 1.22918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417741,-99) , 
10, 311.721, 1, 0, 0.452778,-99) , 
13, 2.3195, 0, 0, 0.608855,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.1076);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36813,-99) , 
2, 122.521, 1, 0, 0.755753,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.399403,-99) , 
10, 303.084, 0, 0, 0.624894,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.123222);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.303382,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 3.42199,-99) , 
3, 0.514493, 0, 0, 1.59823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.775358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432189,-99) , 
7, 702.76, 1, 0, 0.452744,-99) , 
11, 244.054, 1, 0, 0.630782,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.132689);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1.89193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435517,-99) , 
3, 0.249679, 0, 0, 0.824118,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.407141,-99) , 
10, 303.869, 0, 0, 0.65986,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.16194);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.351637,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 2.74995,-99) , 
14, 0.676712, 0, 0, 1.223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422876,-99) , 
6, 3.11551, 0, 0, 0.454175,-99) , 
13, 1.62558, 0, 0, 0.689562,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.222186);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.252326,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 6.3102,-99) , 
6, 3.11343, 0, 0, 2.0541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364911,-99) , 
13, 2.01481, 1, 0, 0.453392,-99) , 
0, 0.00069993, 0, 0, 0.722691,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.27072);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.292972,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 6.31368,-99) , 
9, 0.842535, 0, 0, 2.00105,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412162,-99) , 
14, 0.753818, 0, 0, 0.430501,-99) , 
13, 1.62558, 0, 0, 0.752447,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.260991);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.312477,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 8.95686,-99) , 
10, 523.738, 0, 0, 2.84939,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336437,-99) , 
13, 1.67276, 1, 0, 0.42743,-99) , 
2, 107.457, 1, 0, 0.840085,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.126348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.256283,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 2.27311,-99) , 
4, 0.788795, 1, 0, 1.34763,-99) , 
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.300851,-99) , 
11, 188.186, 0, 0, 0.926439,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.155143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 9.7465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36769,-99) , 
3, 0.172048, 1, 0, 0.401429,-99) , 
3, 0.243294, 0, 0, 0.981332,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0569296);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 0.00069993, 1, -1, 0.350049,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.289169,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 14.426,-99) , 
3, 0.593333, 0, 0, 3.7313,-99) , 
10, 304.094, 1, 0, 1.0575,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0639086);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 0.00059994, 1, -1, 0.36985,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 13.4448,-99) , 
13, 0.993869, 1, 0, 1.09968,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.006974);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28631,-99) , 
3, 0.218034, 1, 0, 0.328965,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.310095,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 15.9402,-99) , 
9, 0.995896, 0, 0, 4.22728,-99) , 
9, 0.456091, 1, 0, 1.14892,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.00654429);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287737,-99) , 
3, 0.218034, 1, 0, 0.329842,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.277451,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 10.6482,-99) , 
5, 1.83672, 0, 0, 4.33546,-99) , 
9, 0.456091, 1, 0, 1.15445,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.00465227);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28908,-99) , 
3, 0.218034, 1, 0, 0.330667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.278765,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 11.3684,-99) , 
5, 1.83672, 0, 0, 4.44175,-99) , 
9, 0.456091, 1, 0, 1.15957,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.00329283);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290037,-99) , 
3, 0.218034, 1, 0, 0.331255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.279701,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 11.946,-99) , 
5, 1.83672, 0, 0, 4.52094,-99) , 
9, 0.456091, 1, 0, 1.16326,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.00232321);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290716,-99) , 
3, 0.218034, 1, 0, 0.331671,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.280365,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 12.3934,-99) , 
5, 1.83672, 0, 0, 4.57894,-99) , 
9, 0.456091, 1, 0, 1.16589,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.02437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 0.00049995, 1, -1, 0.35248,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 10.6238,-99) , 
6, 3.11195, 0, 0, 1.16775,-99)    );
  // itree = 170
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.288951,-99) , 
3, 0.218034, 1, 0, 0.329639,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.277309,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 17.5463,-99) , 
5, 1.85594, 0, 0, 5.27394,-99) , 
9, 0.456091, 1, 0, 1.18864,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_singleClass_boosted_boosted_2017::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_singleClass_boosted_boosted_2017::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
